function playerSpawn () {
    hasSword = 0
    hero = sprites.create(img`
        ........................
        .....ffff...............
        ...fff22fff.............
        ..fff2222fff............
        .fffeeeeeefff...........
        .ffe222222eef...........
        .fe2ffffff2ef...........
        .ffffeeeeffff...........
        ffefbf44fbfeff..........
        fee41fddf14eef..........
        .ffffdddddeef...........
        fddddf444eef............
        fbbbbf2222f4e...........
        fbbbbf2222fd4...........
        .fccf45544f44...........
        ..ffffffff..............
        ....ff..ff..............
        ........................
        ........................
        ........................
        ........................
        ........................
        ........................
        ........................
        `, SpriteKind.Player)
    controller.moveSprite(hero)
    scene.cameraFollowSprite(hero)
    info.setLife(3)
}
function enemySpawn () {
    meanie = sprites.create(img`
        ........................
        ........................
        ........................
        ........................
        ..........ffff..........
        ........ff1111ff........
        .......fb111111bf.......
        .......f11111111f.......
        ......fd11111111df......
        ......fd11111111df......
        ......fddd1111dddf......
        ......fbdbfddfbdbf......
        ......fcdcf11fcdcf......
        .......fb111111bf.......
        ......fffcdb1bdffff.....
        ....fc111cbfbfc111cf....
        ....f1b1b1ffff1b1b1f....
        ....fbfbffffffbfbfbf....
        .........ffffff.........
        ...........fff..........
        ........................
        ........................
        ........................
        ........................
        `, SpriteKind.Enemy)
    meanie.setPosition(randint(0, 250), randint(0, 250))
    meanieLife = 3
    meanie.follow(hero, 30)
}
controller.B.onEvent(ControllerButtonEvent.Pressed, function () {
    hero.setImage(assets.image`shieldup`)
    shieldUp = 1
})
controller.A.onEvent(ControllerButtonEvent.Pressed, function () {
    if (hasSword == 1) {
        hero.setImage(img`
            ........................
            ......ffff..............
            ....fff22fff............
            ...fff2222fff...........
            ..fffeeeeeefff..........
            ..ffe222222eef..........
            ..fe2ffffff2ef..........
            ..ffffeeeeffff..........
            .ffefbf44fbfeff.........
            .fee41fddf14eef.........
            fdfeeddddd4eff..........
            fbffee444edd4e..........
            fbf4f2222edde...........
            fcf.f22cccee............
            .ff.f44cdc4f............
            ....fffddcff............
            .....fddcff.............
            ....cddc................
            ....cdc.................
            ....cc..................
            ........................
            ........................
            ........................
            ........................
            `)
        pause(100)
        hero.setImage(img`
            ........................
            ........................
            .......ff...............
            .....ff22ff.............
            ...fff2222fff...........
            ..fff222222fff..........
            ..fff222222fff..........
            ..feeeeeeeeeeff.........
            .ffe22222222eff.........
            .fffffeeeefffff.........
            fdfefbf44fbfeff.........
            fbfe41fddf14ef..........
            fbffe4dddd4efe..........
            fcfef22222f4e...........
            .ff4f44554f4e...........
            ....ffffffdde...........
            .....ffffedde...........
            ..........ee............
            .........ccc............
            ........cc1cc...........
            .........c1c............
            .........c1c............
            .........c1c............
            .........c1c............
            `)
        pause(100)
        hero.setImage(img`
            ......ffff..............
            ....fff22fff............
            ...fff2222fff...........
            ..fffeeeeeefff..........
            ..ffe222222eef..........
            ..fe2ffffff2ef..........
            ..ffffeeeeffff......ccc.
            .ffefbf44fbfeff....cddc.
            .ffefbf44fbfeff...cddc..
            .fee4dddddd4eef.ccddc...
            fdfeeddddd4eeffecddc....
            fbffee4444ee4fddccc.....
            fbf4f222222f1edde.......
            fcf.f222222f44ee........
            .ff.f445544f............
            ....ffffffff............
            .....ff..ff.............
            ........................
            ........................
            ........................
            ........................
            ........................
            ........................
            ........................
            `)
        pause(100)
        hero.setImage(img`
            ........................
            .....ffff...............
            ...fff22fff.............
            ..fff2222fff............
            .fffeeeeeefff...........
            .ffe222222eef...........
            .fe2ffffff2ef...........
            .ffffeeeeffff...........
            ffefbf44fbfeff..........
            fee41fddf14eef..........
            .ffffdddddeef...........
            fddddf444eef............
            fbbbbf2222f4e...........
            fbbbbf2222fd4...........
            .fccf45544f44...........
            ..ffffffff..............
            ....ff..ff..............
            ........................
            ........................
            ........................
            ........................
            ........................
            ........................
            ........................
            `)
        if (hero.overlapsWith(meanie)) {
            meanieLife += -1
            if (meanieLife == 0) {
                meanie.startEffect(effects.disintegrate)
                sprites.destroy(meanie)
                deads += 1
            }
        }
        if (hero.overlapsWith(meanie2)) {
            meanie2life += -1
            if (meanie2life == 0) {
                meanie2.startEffect(effects.disintegrate)
                sprites.destroy(meanie2)
                deads += 1
            }
        }
        if (hero.overlapsWith(meanie3)) {
            meanie3life += -1
            if (meanie3life == 0) {
                meanie3.startEffect(effects.disintegrate)
                sprites.destroy(meanie3)
                deads += 1
            }
        }
        if (hero.overlapsWith(meanie4)) {
            meanie4life += -1
            if (meanie4life == 0) {
                meanie4.startEffect(effects.disintegrate)
                sprites.destroy(meanie4)
                deads += 1
            }
        }
    }
})
function enemySpawn4 () {
    meanie4 = sprites.create(img`
        ........................
        ........................
        ........................
        ........................
        ..........ffff..........
        ........ff1111ff........
        .......fb111111bf.......
        .......f11111111f.......
        ......fd11111111df......
        ......fd11111111df......
        ......fddd1111dddf......
        ......fbdbfddfbdbf......
        ......fcdcf11fcdcf......
        .......fb111111bf.......
        ......fffcdb1bdffff.....
        ....fc111cbfbfc111cf....
        ....f1b1b1ffff1b1b1f....
        ....fbfbffffffbfbfbf....
        .........ffffff.........
        ...........fff..........
        ........................
        ........................
        ........................
        ........................
        `, SpriteKind.Enemy)
    meanie4.setPosition(randint(0, 250), randint(0, 250))
    meanie4life = 3
    meanie4.follow(hero, 70)
}
function enemySpawn2 () {
    meanie2 = sprites.create(img`
        ........................
        ........................
        ........................
        ........................
        ..........ffff..........
        ........ff1111ff........
        .......fb111111bf.......
        .......f11111111f.......
        ......fd11111111df......
        ......fd11111111df......
        ......fddd1111dddf......
        ......fbdbfddfbdbf......
        ......fcdcf11fcdcf......
        .......fb111111bf.......
        ......fffcdb1bdffff.....
        ....fc111cbfbfc111cf....
        ....f1b1b1ffff1b1b1f....
        ....fbfbffffffbfbfbf....
        .........ffffff.........
        ...........fff..........
        ........................
        ........................
        ........................
        ........................
        `, SpriteKind.Enemy)
    meanie2.setPosition(randint(0, 250), randint(0, 250))
    meanie2life = 3
    meanie2.follow(hero, 50)
}
scene.onOverlapTile(SpriteKind.Player, sprites.dungeon.chestClosed, function (sprite, location) {
    if (hasSword == 0) {
        hasSword = 1
    }
})
info.onLifeZero(function () {
    game.splash("You died!")
    sprites.destroyAllSpritesOfKind(SpriteKind.Player)
    sprites.destroyAllSpritesOfKind(SpriteKind.Enemy)
    playerSpawn()
    enemySpawn()
    enemySpawn2()
    enemySpawn3()
    enemySpawn4()
    gameStart()
    swordSpawn()
    deads = 0
})
function enemySpawn3 () {
    meanie3 = sprites.create(img`
        ........................
        ........................
        ........................
        ........................
        ..........ffff..........
        ........ff1111ff........
        .......fb111111bf.......
        .......f11111111f.......
        ......fd11111111df......
        ......fd11111111df......
        ......fddd1111dddf......
        ......fbdbfddfbdbf......
        ......fcdcf11fcdcf......
        .......fb111111bf.......
        ......fffcdb1bdffff.....
        ....fc111cbfbfc111cf....
        ....f1b1b1ffff1b1b1f....
        ....fbfbffffffbfbfbf....
        .........ffffff.........
        ...........fff..........
        ........................
        ........................
        ........................
        ........................
        `, SpriteKind.Enemy)
    meanie3.setPosition(randint(0, 250), randint(0, 250))
    meanie3life = 3
    meanie3.follow(hero, 35)
}
controller.B.onEvent(ControllerButtonEvent.Released, function () {
    hero.setImage(img`
        ........................
        .....ffff...............
        ...fff22fff.............
        ..fff2222fff............
        .fffeeeeeefff...........
        .ffe222222eef...........
        .fe2ffffff2ef...........
        .ffffeeeeffff...........
        ffefbf44fbfeff..........
        fee41fddf14eef..........
        .ffffdddddeef...........
        fddddf444eef............
        fbbbbf2222f4e...........
        fbbbbf2222fd4...........
        .fccf45544f44...........
        ..ffffffff..............
        ....ff..ff..............
        ........................
        ........................
        ........................
        ........................
        ........................
        ........................
        ........................
        `)
    shieldUp = 0
})
function swordSpawn () {
    sword = sprites.create(assets.image`sword`, SpriteKind.Food)
    sword.setPosition(randint(0, 250), randint(0, 250))
}
sprites.onOverlap(SpriteKind.Player, SpriteKind.Food, function (sprite, otherSprite) {
    hasSword = 1
    game.splash("Found: 1 Iron Sword")
    sword.startEffect(effects.halo)
    sprites.destroy(sword)
})
function lootSpawn () {
    sword = sprites.create(img`
        . . . . . b b b b b b . . . . . 
        . . . b b 9 9 9 9 9 9 b b . . . 
        . . b b 9 9 9 9 9 9 9 9 b b . . 
        . b b 9 d 9 9 9 9 9 9 9 9 b b . 
        . b 9 d 9 9 9 9 9 1 1 1 9 9 b . 
        b 9 d d 9 9 9 9 9 1 1 1 9 9 9 b 
        b 9 d 9 9 9 9 9 9 1 1 1 9 9 9 b 
        b 9 3 9 9 9 9 9 9 9 9 9 1 9 9 b 
        b 5 3 d 9 9 9 9 9 9 9 9 9 9 9 b 
        b 5 3 3 9 9 9 9 9 9 9 9 9 d 9 b 
        b 5 d 3 3 9 9 9 9 9 9 9 d d 9 b 
        . b 5 3 3 3 d 9 9 9 9 d d 5 b . 
        . b d 5 3 3 3 3 3 3 3 d 5 b b . 
        . . b d 5 d 3 3 3 3 5 5 b b . . 
        . . . b b 5 5 5 5 5 5 b b . . . 
        . . . . . b b b b b b . . . . . 
        `, SpriteKind.Food)
    meanie2.setPosition(randint(0, 100), randint(0, 100))
    hasSword = 1
}
function gameStart () {
    game.splash("FIND THE SWORD, KILL THE ENEMIES. YOU HAVE 30 SECONDS. A TO ATTACK, B TO HOLD UP SHIELD.")
    info.startCountdown(30)
}
let sword: Sprite = null
let meanie4life = 0
let meanie4: Sprite = null
let meanie3life = 0
let meanie3: Sprite = null
let meanie2life = 0
let meanie2: Sprite = null
let shieldUp = 0
let meanieLife = 0
let meanie: Sprite = null
let hero: Sprite = null
let hasSword = 0
let deads = 0
deads = 0
tiles.setCurrentTilemap(tilemap`level1`)
playerSpawn()
enemySpawn()
enemySpawn2()
enemySpawn3()
enemySpawn4()
gameStart()
swordSpawn()
game.onUpdateInterval(1000, function () {
    if (meanie.overlapsWith(hero)) {
        hero.startEffect(effects.hearts, 500)
        if (shieldUp == 0) {
            info.changeLifeBy(-1)
        }
    }
    if (meanie2.overlapsWith(hero)) {
        hero.startEffect(effects.hearts, 500)
        if (shieldUp == 0) {
            info.changeLifeBy(-1)
        }
    }
    if (meanie3.overlapsWith(hero)) {
        hero.startEffect(effects.hearts, 500)
        if (shieldUp == 0) {
            info.changeLifeBy(-1)
        }
    }
    if (meanie4.overlapsWith(hero)) {
        hero.startEffect(effects.hearts, 500)
        if (shieldUp == 0) {
            info.changeLifeBy(-1)
        }
    }
    if (deads == 4) {
        game.gameOver(true)
        deads = 0
    }
})
